### ISSUE TITLE
Refactor the amc into a specific class

### ISSUE THREAD

**Issue by aerostitch** [tubemogul/puppet-aerospike#32]
Move it out of the base `aerospike` class to a `aerospike::amc` could make more sense as you should be able to have an amc on a box totally separated, without any aerospike server installed on it.
It would also make the code cleaner.
We also need to avoid breaking the compatiblity with the current way of declaring the amc install params (we deprecate it in the version that ships this change as a 1st step)

Also add the configuration of the amc configuration (/etc/amc/config/*)

**Comment by Halytskyi** [comment]
Done, in "master" branch now and will be in next release.
